services:
  pgadmin:
      image: dpage/pgadmin4:7.1
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@domain.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_ADDRESS: 0.0.0.0
        PGADMIN_LISTEN_PORT: 80
      ports:
        - "9000:80"
      networks:
        - keycloak_dev_network
