services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak_dev_network
      
  postgres:
      image: postgres:15.3
      command: postgres -c 'max_connections=100'
      volumes:
        - pgdata_keycloak:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      healthcheck:
        test: "exit 0"
      ports:
        - "5433:5432"
      networks:
        - keycloak_dev_network
